### ISSUE TITLE
ng-include doesn't seem to work

### ISSUE THREAD

**Issue by Deklin** [dpiccone/ng-pageslide#129]
I tried this with ng-include so i can re-use my inner content for mobile and non-mobile modes and it doesn't seem to work properly w/ ng-include. Is this a known issue? (if you require a fiddle or plnkr i'll gladly create one)

**Comment by Deklin** [comment]
`angular.js:13920 Error: You need to have content inside the <pageslide>
    at Object.link (http://localhost:9000/csa/html-lib/js/3rdparty/angular/addons/pageslide/angular-pageslide-directive.min.js:2:3237)
    at http://localhost:9000/csa/html-lib/js/3rdparty/angular/angular.min.js:16:71
    at http://localhost:9000/csa/html-lib/js/3rdparty/angular/angular.min.js:81:33
    at la (http://localhost:9000/csa/html-lib/js/3rdparty/angular/angular.min.js:81:90)
    at p (http://localhost:9000/csa/html-lib/js/3rdparty/angular/angular.min.js:66:341)
    at g (http://localhost:9000/csa/html-lib/js/3rdparty/angular/angular.min.js:58:481)
    at g (http://localhost:9000/csa/html-lib/js/3rdparty/angular/angular.min.js:58:498)
    at g (http://localhost:9000/csa/html-lib/js/3rdparty/angular/angular.min.js:58:498)
    at g (http://localhost:9000/csa/html-lib/js/3rdparty/angular/angular.min.js:58:498)
    at g (http://localhost:9000/csa/html-lib/js/3rdparty/angular/angular.min.js:58:498) <pageslide ps-open="navigationSlideOutOpened" ps-auto-close="true" ps-side="left" ps-container="layout-main-body" ps-class="layout-main-navigation-slideout" ps-body-class="true" class="ng-isolate-scope layout-main-navigation-slideout">(anonymous function) @ angular.js:13920(anonymous function) @ angular.js:10467la @ angular.js:9936p @ angular.js:9335g @ angular.js:8620g @ angular.js:8623g @ angular.js:8623g @ angular.js:8623g @ angular.js:8623(anonymous function) @ angular.js:8500(anonymous function) @ angular-ui-router.js:4089(anonymous function) @ angular.js:1247la @ angular.js:9934p @ angular.js:9335g @ angular.js:8620(anonymous function) @ angular.js:8500(anonymous function) @ angular.js:8844updateView @ angular-ui-router.js:4021(anonymous function) @ angular-ui-router.js:3959$broadcast @ angular.js:18005$state.transition.resolved.then.$state.transition @ angular-ui-router.js:3352(anonymous function) @ angular.js:16383$eval @ angular.js:17682$digest @ angular.js:17495$apply @ angular.js:17790(anonymous function) @ angular.js:1761invoke @ angular.js:4718c @ angular.js:1759Bc.ca.resumeBootstrap @ angular.js:1787(anonymous function) @ main.js:24i @ jquery.min.js:2add @ jquery.min.js:2n.fn.ready @ jquery.min.js:2(anonymous function) @ main.js:23execCb @ require.js:29check @ require.js:18(anonymous function) @ require.js:22(anonymous function) @ require.js:7(anonymous function) @ require.js:23y @ require.js:6emit @ require.js:23check @ require.js:19(anonymous function) @ require.js:22(anonymous function) @ require.js:7(anonymous function) @ require.js:23y @ require.js:6emit @ require.js:23check @ require.js:19(anonymous function) @ require.js:22(anonymous function) @ require.js:7(anonymous function) @ require.js:23y @ require.js:6emit @ require.js:23check @ require.js:19(anonymous function) @ require.js:22(anonymous function) @ require.js:7(anonymous function) @ require.js:23y @ require.js:6emit @ require.js:23check @ require.js:19(anonymous function) @ require.js:22(anonymous function) @ require.js:7(anonymous function) @ require.js:23y @ require.js:6emit @ require.js:23check @ require.js:19enable @ require.js:23init @ require.js:16(anonymous function) @ require.js:20(anonymous function) @ require.js:7finishLoad @ text-2.0.14.js:152(anonymous function) @ text-2.0.14.js:188xhr.onreadystatechange @ text-2.0.14.js:300
hpe_logo_minimal.png:1 GET http://localhost:9000/csa/images/library/hpe_logo_minimal.png 404 (Not Found)`

**Comment by Deklin** [comment]
Ok I solved it.
<pageslide ps-open="navigationSlideOutOpened" ps-auto-close="true" ps-side="left" ps-container="layout-main-body" ps-class="layout-main-navigation-slideout" ps-body-class="true">
                    <div>
                        <ng-include src="'DesignContainersMainNavigation.html'"></ng-include> 
                    </div>
                </pageslide>


can't just have ng-include directly, need a wrapping div.
