### ISSUE TITLE
Appending to a container does not seem to work

### ISSUE THREAD

**Issue by snowman18** [dpiccone/ng-pageslide#81]
I have an ngDialog

However when I run page slide it attaches it to the parent. So I added an id to the dialog window, but get the following message.

TypeError: Cannot read property 'appendChild' of null
    at link (http://godzilla.tennissource.net/bower_components/angular-pageslide-directive/dist/angular-pageslide-directive.min.js:2:2630)
    at http://godzilla.tennissource.net/bower_components/angular/angular.min.js:73:33
    at aa (http://godzilla.tennissource.net/bower_components/angular/angular.min.js:73:90)
    at K (http://godzilla.tennissource.net/bower_components/angular/angular.min.js:62:39)
    at g (http://godzilla.tennissource.net/bower_components/angular/angular.min.js:54:410)
    at K (http://godzilla.tennissource.net/bower_components/angular/angular.min.js:61:488)
    at g (http://godzilla.tennissource.net/bower_components/angular/angular.min.js:54:410)
    at g (http://godzilla.tennissource.net/bower_components/angular/angular.min.js:54:433)
    at g (http://godzilla.tennissource.net/bower_components/angular/angular.min.js:54:433)
    at http://godzilla.tennissource.net/bower_components/angular/angular.min.js:53:480 <div pageslide="" ps-open="checked" ps-container="mycheckin" class="ng-isolate-scope ng-pageslide" style="z-index: 1000;width: 0px; height: 100%; overflow: hidden; transition-duration: 0.5s; transition-property: width, height; top: 0px; bottom: 0px; right: 0px;">

**Comment by zp-j** [comment]
Hi @snowman18 , I came across the same issue just now, then I found that it was my fault. 

If you want to append slide panel to a certain container, you can use `ps-container` to indicate which container to append to. For example:

```html
<!-- This is your container -->
<div id="myContainer"></div>

<!-- Slide panel -->
<pageslide
  ps-side="right"
  ps-open="checked"
  ps-key-listener="true"
  ps-size="400px"
  ps-container="myContainer"   ( <== Tell pageslide which container to append to )
  >
  <div class="slidePanel">
    <p>some random content...</p>
  </div>
</pageslide>
```
